version: 1
project:
  repo: "HenryAllen04/Dumpy"
  defaultBranch: "main"

capture:
  devices:
    - name: desktop
      width: 1440
      height: 900
    - name: mobile
      width: 390
      height: 844
  fullPage: true
  timeoutMs: 30000
  waitUntil: networkidle
  disableAnimations: true

routes:
  include:
    - "/"
  exclude:
    - "/api/*"
    - "/auth/callback*"

discovery:
  sitemap:
    enabled: true
    path: "/sitemap.xml"
  maxRoutes: 200

output:
  publicBaseUrl: "https://assets.dumpy.ai"
